DEF DEBUG = 0

# XXX: To use Future implemented in C, you need a modified
# version of asyncio.
DEF USE_C_FUTURE = 1

DEF UV_STREAM_RECV_BUF_SIZE = 65536

DEF FLOW_CONTROL_HIGH_WATER = 65536
DEF FLOW_CONTROL_LOW_WATER = 16384

DEF MAX_THREADPOOL_WORKERS = 5
